# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephen O'Kennedy
email: okenneds@tcd.ie
description: > # this means to ignore newlines until "baseurl:"
  Some say "I'm a visionary" or "a person ahead of his time". Others
  ,quite rightly, call me a jackass.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenokennedy.me" # the base hostname & protocol for your site
enforce_ssl: stephenokennedy.me
twitter_username: jekyllrb
github_username:  stephenoken

# Build settings
markdown: kramdown

gems:
  - jekyll-time-to-read
